version: '3.8'

services:
  newblazorwebapp-blazor:
    image: mycompanyname/newblazorwebapp-blazor:latest
    container_name: newblazorwebapp-blazor
    build:
      context: ../../
      dockerfile: src/NewBlazorWebApp.Blazor/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=039af270-522b-4321-ad1b-adf52b00443b
      - App__SelfUrl=https://localhost:44314
      - AuthServer__RequireHttpsMetadata=false      
      - AuthServer__Authority=http://newblazorwebapp-blazor
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=NewBlazorWebApp;Pooling=false;
    ports:
      - "44314:443"
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  db-migrator:
    image: mycompanyname/newblazorwebapp-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/NewBlazorWebApp.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__NewBlazorWebApp_BlazorServerTiered__RootUrl=https://localhost:44314
      - OpenIddict__Applications__NewBlazorWebApp_Swagger__RootUrl=https://localhost:44396
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=NewBlazorWebApp;Pooling=false;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - abp-network
  
  postgres:
    container_name: postgres-db
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myPassw0rd"
    volumes:
      - postgres_data:/var/opt/postgres
    networks: 
      - abp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5    

volumes:
  postgres_data:
    name: newblazorwebapp_postgres_data
networks:
  abp-network:
    name: newblazorwebapp-network
    driver: bridge
