using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using NewBlazorWebApp.Permissions;
using NewBlazorWebApp.Customers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using NewBlazorWebApp.Shared;
using Volo.Abp.BlobStoring;

namespace NewBlazorWebApp.Customers
{
    public class CustomersAppService : CustomersAppServiceBase, ICustomersAppService
    {
        //<suite-custom-code-autogenerated>
        public CustomersAppService(ICustomerRepository customerRepository, CustomerManager customerManager, IDistributedCache<CustomerDownloadTokenCacheItem, string> downloadTokenCache, IRepository<AppFileDescriptors.AppFileDescriptor, Guid> appFileDescriptorRepository, IBlobContainer<CustomerFileContainer> blobContainer)
            : base(customerRepository, customerManager, downloadTokenCache, appFileDescriptorRepository, blobContainer)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}