using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace NewBlazorWebApp.Customers
{
    public class Customer : CustomerBase
    {
        //<suite-custom-code-autogenerated>
        protected Customer()
        {

        }

        public Customer(Guid id, string code, float balance, Guid documentsId, string? name = null, string? address = null)
            : base(id, code, balance, documentsId, name, address)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}