using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace NewBlazorWebApp.Customers
{
    public class CustomerManager : CustomerManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CustomerManager(ICustomerRepository customerRepository)
            : base(customerRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}